version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-mac:
    macos:
      xcode: 11.3.1
    steps:
      - checkout
      - run:
          command: ./install.py --all
          name: Build
  build-linux:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ./install.py --all
          name: Build

workflows:
  main:
    jobs:
      - build-mac
      - build-linux
